In [14]:
# Dependencies and setup
import pandas as pd
import csv
import pymongo

In [15]:
conn = conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Define the 'classDB' database in Mongo
db = client.TN_cities_DB

# Declare the collection
cities = db.cities

In [16]:
# Data files
region_data = "Resources/All_homes.csv"
score_data = "Resources/data_ACT-Data-by-District-2013-14.csv"

In [17]:
# Convert to region_data to df
region_df = pd.read_csv(region_data, index_col = 0)

In [18]:
# Filter region_df by Tennessee towns only
TN_towns = region_df.loc[region_df["State"] == "TN"].set_index('CountyName')
TN_towns.head()

,RegionName,State,Metro,SizeRank,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,...,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08
CountyName,,,,,,,,,,,,,,,,,,,,,
Shelby,Memphis,TN,Memphis,15,60600.0,60500.0,60700.0,60800.0,61000.0,61300.0,...,69600,69800,69900,70800,72000,73100,74300,75100,75600,76200
Davidson,Nashville,TN,Nashville,23,83100.0,83800.0,84800.0,85900.0,86500.0,87000.0,...,189300,191400,193300,195100,196800,198400,200300,202400,205000,207200
Knox,Knoxville,TN,Knoxville,89,65700.0,66000.0,66500.0,66900.0,67100.0,67300.0,...,118800,119100,118900,118700,118400,117600,117400,118000,118900,119700
Hamilton,Chattanooga,TN,Chattanooga,141,59200.0,59700.0,60300.0,60900.0,61600.0,62100.0,...,121900,122400,122700,123100,123300,123500,123900,125100,126900,128300
Rutherford,Murfreesboro,TN,Nashville,165,88400.0,89300.0,90300.0,91200.0,91800.0,92500.0,...,177400,178400,179600,181400,183200,184600,185400,186500,188100,189800

In [19]:
# Convert to score_data to df & format
score_df = pd.read_csv(score_data, header = [2,3])
score_df.columns = score_df.columns.map('_'.join)
score_df.rename(columns={'Unnamed: 0_level_0_System':'Region'}, inplace=True )
score_df["Region"] = score_df["Region"].str.title()
score_df.head()

,Region,Composite_2013 Including Extended Time,Composite_2013 Standard Time Only,Composite_2014 Including Extended Time,English_2013 Including Extended Time,English_2013 Standard Time Only,English_2014 Including Extended Time,Math_2013 Including Extended Time,Math_2013 Standard Time Only,Math_2014 Including Extended Time,Reading_2013 Including Extended Time,Reading_2013 Standard Time Only,Reading_2014 Including Extended Time,Science_2013 Including Extended Time,Science_2013 Standard Time Only,Science_2014 Including Extended Time
0,State,19.0,19.3,19.3,18.7,19.0,18.9,18.7,18.8,18.8,19.3,19.5,19.6,19.1,19.3,19.2
1,Anderson School District,18.9,19.1,19.3,18.5,18.7,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
2,Alcoa City Schools,21.6,22.2,21.3,21.8,22.6,21.5,20.9,21.5,20.8,22.1,22.5,21.5,21.3,21.7,20.9
3,Bedford County School District,18.0,18.3,18.4,17.4,17.8,18.2,18.0,18.3,18.2,18.0,18.3,18.5,17.9,18.2,18.4
4,Benton Co Board Of Education,18.4,19.2,19.0,17.7,18.8,18.3,18.4,19.0,18.4,18.5,19.3,19.6,18.4,19.1,19.1

In [20]:
city = []
for i in score_df["Region"]:
    x = i.split(" ")[0]
    city.append(x)
    
score_df['District Abb.'] = city
score_df.set_index('District Abb.', inplace = True)
score_df.head()

,Region,Composite_2013 Including Extended Time,Composite_2013 Standard Time Only,Composite_2014 Including Extended Time,English_2013 Including Extended Time,English_2013 Standard Time Only,English_2014 Including Extended Time,Math_2013 Including Extended Time,Math_2013 Standard Time Only,Math_2014 Including Extended Time,Reading_2013 Including Extended Time,Reading_2013 Standard Time Only,Reading_2014 Including Extended Time,Science_2013 Including Extended Time,Science_2013 Standard Time Only,Science_2014 Including Extended Time
District Abb.,,,,,,,,,,,,,,,,
State,State,19.0,19.3,19.3,18.7,19.0,18.9,18.7,18.8,18.8,19.3,19.5,19.6,19.1,19.3,19.2
Anderson,Anderson School District,18.9,19.1,19.3,18.5,18.7,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
Alcoa,Alcoa City Schools,21.6,22.2,21.3,21.8,22.6,21.5,20.9,21.5,20.8,22.1,22.5,21.5,21.3,21.7,20.9
Bedford,Bedford County School District,18.0,18.3,18.4,17.4,17.8,18.2,18.0,18.3,18.2,18.0,18.3,18.5,17.9,18.2,18.4
Benton,Benton Co Board Of Education,18.4,19.2,19.0,17.7,18.8,18.3,18.4,19.0,18.4,18.5,19.3,19.6,18.4,19.1,19.1

In [21]:
merged_df = pd.merge(TN_towns, score_df, left_index = True, right_index = True)
merged_df.head()
#merged_df.to_csv("Resources/merged_TN_data.csv")

,RegionName,State,Metro,SizeRank,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,...,English_2014 Including Extended Time,Math_2013 Including Extended Time,Math_2013 Standard Time Only,Math_2014 Including Extended Time,Reading_2013 Including Extended Time,Reading_2013 Standard Time Only,Reading_2014 Including Extended Time,Science_2013 Including Extended Time,Science_2013 Standard Time Only,Science_2014 Including Extended Time
Anderson,Oak Ridge,TN,Knoxville,1474,71100.0,72200.0,72700.0,72900.0,72800.0,73000.0,...,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
Anderson,Clinton,TN,Knoxville,1493,63600.0,64300.0,64200.0,63700.0,63300.0,62900.0,...,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
Anderson,Lake City,TN,Knoxville,7744,44800.0,44600.0,44900.0,45300.0,45400.0,44300.0,...,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
Anderson,Heiskell,TN,Knoxville,7801,63800.0,63900.0,63500.0,63000.0,63500.0,64200.0,...,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5
Anderson,Andersonville,TN,Knoxville,8404,69300.0,70700.0,71900.0,72900.0,73800.0,74200.0,...,18.9,18.9,19.0,19.0,18.8,19.0,19.5,19.0,19.1,19.5

In [22]:
clean_df = merged_df.drop(columns=['1996-04','1996-05','1996-06','1996-07','1996-08','1996-09','1996-10','1996-11','1996-12','1997-01','1997-02','1997-03','1997-04','1997-05','1997-06','1997-07','1997-08','1997-09','1997-10','1997-11','1997-12','1998-01','1998-02','1998-03','1998-04','1998-05','1998-06','1998-07','1998-08','1998-09','1998-10','1998-11','1998-12','1999-01','1999-02','1999-03','1999-04','1999-05','1999-06','1999-07','1999-08','1999-09','1999-10','1999-11','1999-12','2000-01','2000-02','2000-03','2000-04','2000-05','2000-06','2000-07','2000-08','2000-09','2000-10','2000-11','2000-12','2001-01','2001-02','2001-03','2001-04','2001-05','2001-06','2001-07','2001-08','2001-09','2001-10','2001-11','2001-12','2002-01','2002-02','2002-03','2002-04','2002-05','2002-06','2002-07','2002-08','2002-09','2002-10','2002-11','2002-12','2003-01','2003-02','2003-03','2003-04','2003-05','2003-06','2003-07','2003-08','2003-09','2003-10','2003-11','2003-12','2004-01','2004-02','2004-03','2004-04','2004-05','2004-06','2004-07','2004-08','2004-09','2004-10','2004-11','2004-12','2005-01','2005-02','2005-03','2005-04','2005-05','2005-06','2005-07','2005-08','2005-09','2005-10','2005-11','2005-12','2006-01','2006-02','2006-03','2006-04','2006-05','2006-06','2006-07','2006-08','2006-09','2006-10','2006-11','2006-12','2007-01','2007-02','2007-03','2007-04','2007-05','2007-06','2007-07','2007-08','2007-09','2007-10','2007-11','2007-12','2008-01','2008-02','2008-03','2008-04','2008-05','2008-06','2008-07','2008-08','2008-09','2008-10','2008-11','2008-12','2009-01','2009-02','2009-03','2009-04','2009-05','2009-06','2009-07','2009-08','2009-09','2009-10','2009-11','2009-12','2010-01','2010-02','2010-03','2010-04','2010-05','2010-06','2010-07','2010-08','2010-09','2010-10','2010-11','2010-12','2011-01','2011-02','2011-03','2011-04','2011-05','2011-06','2011-07','English_2013 Including Extended Time','English_2013 Standard Time Only','English_2014 Including Extended Time','Math_2013 Including Extended Time','Math_2013 Standard Time Only','Math_2014 Including Extended Time','Reading_2013 Including Extended Time','Reading_2013 Standard Time Only','Reading_2014 Including Extended Time','Science_2013 Including Extended Time','Science_2013 Standard Time Only','Science_2014 Including Extended Time'])
clean_df.head()

,RegionName,State,Metro,SizeRank,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,...,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,Region,Composite_2013 Including Extended Time,Composite_2013 Standard Time Only,Composite_2014 Including Extended Time
Anderson,Oak Ridge,TN,Knoxville,1474,113700.0,112600.0,112300.0,112100.0,111600.0,111700.0,...,116500,116700,116900,116900,117200,117400,Anderson School District,18.9,19.1,19.3
Anderson,Clinton,TN,Knoxville,1493,109000.0,109100.0,109800.0,110700.0,110900.0,110500.0,...,114800,115300,115400,115400,115200,115000,Anderson School District,18.9,19.1,19.3
Anderson,Lake City,TN,Knoxville,7744,72700.0,73100.0,73600.0,74700.0,75800.0,76500.0,...,81500,81300,81500,81700,82300,83200,Anderson School District,18.9,19.1,19.3
Anderson,Heiskell,TN,Knoxville,7801,113600.0,114300.0,114700.0,114800.0,114300.0,113600.0,...,117200,117200,117000,117200,118200,119500,Anderson School District,18.9,19.1,19.3
Anderson,Andersonville,TN,Knoxville,8404,138900.0,139700.0,140300.0,140500.0,139400.0,137500.0,...,150900,150300,150500,150800,150700,150300,Anderson School District,18.9,19.1,19.3

In [23]:
CAGR = ((clean_df['2016-08']/clean_df['2011-08'])**(1/5))-1

In [24]:
clean_df['CAGR'] = CAGR
clean_df = clean_df.reset_index()
clean_df.head()

,index,RegionName,State,Metro,SizeRank,2011-08,2011-09,2011-10,2011-11,2011-12,...,2016-04,2016-05,2016-06,2016-07,2016-08,Region,Composite_2013 Including Extended Time,Composite_2013 Standard Time Only,Composite_2014 Including Extended Time,CAGR
0,Anderson,Oak Ridge,TN,Knoxville,1474,113700.0,112600.0,112300.0,112100.0,111600.0,...,116700,116900,116900,117200,117400,Anderson School District,18.9,19.1,19.3,0.006425
1,Anderson,Clinton,TN,Knoxville,1493,109000.0,109100.0,109800.0,110700.0,110900.0,...,115300,115400,115400,115200,115000,Anderson School District,18.9,19.1,19.3,0.010774
2,Anderson,Lake City,TN,Knoxville,7744,72700.0,73100.0,73600.0,74700.0,75800.0,...,81300,81500,81700,82300,83200,Anderson School District,18.9,19.1,19.3,0.027348
3,Anderson,Heiskell,TN,Knoxville,7801,113600.0,114300.0,114700.0,114800.0,114300.0,...,117200,117000,117200,118200,119500,Anderson School District,18.9,19.1,19.3,0.010178
4,Anderson,Andersonville,TN,Knoxville,8404,138900.0,139700.0,140300.0,140500.0,139400.0,...,150300,150500,150800,150700,150300,Anderson School District,18.9,19.1,19.3,0.015901

In [25]:
for index,row in clean_df.iterrows():
    dict1 = {
        "Metro": clean_df['Metro'][index],
        "Region": clean_df["RegionName"][index],
        "School Scores": [clean_df['Composite_2013 Including Extended Time'][index], clean_df['Composite_2013 Standard Time Only'][index], clean_df['Composite_2014 Including Extended Time'][index]],
        "CAGR": clean_df['CAGR'][index]}
    cities.insert_one(dict1)

In [26]:
results = cities.find()
for result in results:
    print(result)

{'_id': ObjectId('5f4eeeebdb91df5fb0c3c890'), 'Metro': 'Knoxville', 'Region': 'Oak Ridge', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': 0.0064252552842696264}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c891'), 'Metro': 'Knoxville', 'Region': 'Clinton', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': 0.010774480346176896}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c892'), 'Metro': 'Knoxville', 'Region': 'Lake City', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': 0.027348480887085413}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c893'), 'Metro': 'Knoxville', 'Region': 'Heiskell', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': 0.010178020272250343}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c894'), 'Metro': 'Knoxville', 'Region': 'Andersonville', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': 0.015900904440288022}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c895'), 'Metro': 'Knoxville', 'Region': 'Briceville', 'School Scores': ['18.9', '19.1', '19.3'], 'CAGR': -0.0720281451298731}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c896'), 'Metro': 'Shelbyville', 'Region': 'Shelbyville', 'School Scores': ['18.0', '18.3', '18.4'], 'CAGR': 0.05331302437898411}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c897'), 'Metro': 'Shelbyville', 'Region': 'Bell Buckle', 'School Scores': ['18.0', '18.3', '18.4'], 'CAGR': 0.07182469568951455}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c898'), 'Metro': 'Shelbyville', 'Region': 'Unionville', 'School Scores': ['18.0', '18.3', '18.4'], 'CAGR': 0.05965232979786261}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c899'), 'Metro': 'Shelbyville', 'Region': 'Wartrace', 'School Scores': ['18.0', '18.3', '18.4'], 'CAGR': 0.0733422385169149}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89a'), 'Metro': 'Knoxville', 'Region': 'Maryville', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.030566025042693568}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89b'), 'Metro': 'Knoxville', 'Region': 'Alcoa', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.02615981953607016}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89c'), 'Metro': 'Knoxville', 'Region': 'Friendsville', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.02101016596895744}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89d'), 'Metro': 'Knoxville', 'Region': 'Louisville', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.04527650122312732}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89e'), 'Metro': 'Knoxville', 'Region': 'Walland', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.017378983017688254}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c89f'), 'Metro': 'Knoxville', 'Region': 'Townsend', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.005392266258614775}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a0'), 'Metro': 'Knoxville', 'Region': 'Tallassee', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': -0.01556586513744429}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a1'), 'Metro': 'Knoxville', 'Region': 'Rockford', 'School Scores': ['19.8', '20.2', '19.7'], 'CAGR': 0.03319227211393505}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a2'), 'Metro': 'Cleveland', 'Region': 'Cleveland', 'School Scores': ['18.2', '18.5', '18.9'], 'CAGR': 0.028418761521646463}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a3'), 'Metro': 'Cleveland', 'Region': 'Mc Donald', 'School Scores': ['18.2', '18.5', '18.9'], 'CAGR': 0.01717432498522009}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a4'), 'Metro': 'Cleveland', 'Region': 'Charleston', 'School Scores': ['18.2', '18.5', '18.9'], 'CAGR': 0.028237648410646354}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a5'), 'Metro': 'Cleveland', 'Region': 'Georgetown', 'School Scores': ['18.2', '18.5', '18.9'], 'CAGR': 0.02806218550242634}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a6'), 'Metro': 'Knoxville', 'Region': 'Lafollette', 'School Scores': ['17.3', '17.7', '17.5'], 'CAGR': 0.050108985941962336}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a7'), 'Metro': 'Knoxville', 'Region': 'Jacksboro', 'School Scores': ['17.3', '17.7', '17.5'], 'CAGR': 0.027934194526028522}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a8'), 'Metro': 'Knoxville', 'Region': 'Jellico', 'School Scores': ['17.3', '17.7', '17.5'], 'CAGR': 0.04861016738492974}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8a9'), 'Metro': 'Knoxville', 'Region': 'Caryville', 'School Scores': ['17.3', '17.7', '17.5'], 'CAGR': 0.024328248200959246}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8aa'), 'Metro': 'Nashville', 'Region': 'Woodbury', 'School Scores': ['17.3', '17.6', '17.9'], 'CAGR': 0.05408916015652432}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ab'), 'Metro': 'Nashville', 'Region': 'Bradyville', 'School Scores': ['17.3', '17.6', '17.9'], 'CAGR': 0.06193511306039623}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ac'), 'Metro': 'Johnson City', 'Region': 'Elizabethton', 'School Scores': ['17.6', '17.8', '18.2'], 'CAGR': 0.02658754378333783}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ad'), 'Metro': 'Johnson City', 'Region': 'Roan Mountain', 'School Scores': ['17.6', '17.8', '18.2'], 'CAGR': -0.010391865990172944}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ae'), 'Metro': 'Johnson City', 'Region': 'Hampton', 'School Scores': ['17.6', '17.8', '18.2'], 'CAGR': -0.00021039345435303058}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8af'), 'Metro': 'Johnson City', 'Region': 'Watauga', 'School Scores': ['17.6', '17.8', '18.2'], 'CAGR': 0.014790673606678073}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b0'), 'Metro': 'Nashville', 'Region': 'Kingston Springs', 'School Scores': ['18.7', '19.1', '19.4'], 'CAGR': 0.053112526255790105}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b1'), 'Metro': 'Nashville', 'Region': 'Pleasant View', 'School Scores': ['18.7', '19.1', '19.4'], 'CAGR': 0.03213121685224274}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b2'), 'Metro': 'Nashville', 'Region': 'Ashland City', 'School Scores': ['18.7', '19.1', '19.4'], 'CAGR': 0.021349861995071828}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b3'), 'Metro': 'Nashville', 'Region': 'Pegram', 'School Scores': ['18.7', '19.1', '19.4'], 'CAGR': 0.04090522271239405}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b4'), 'Metro': 'Nashville', 'Region': 'Chapmansboro', 'School Scores': ['18.7', '19.1', '19.4'], 'CAGR': 0.030485101842841145}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b5'), 'Metro': 'Jackson', 'Region': 'Henderson', 'School Scores': ['18.8', '19.0', '19.2'], 'CAGR': 0.02226529000995714}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b6'), 'Metro': 'Jackson', 'Region': 'Enville', 'School Scores': ['18.8', '19.0', '19.2'], 'CAGR': 0.024944477369447604}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b7'), 'Metro': nan, 'Region': 'Speedwell', 'School Scores': ['17.4', '17.9', '18.2'], 'CAGR': 0.00676737599945576}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b8'), 'Metro': 'Newport', 'Region': 'Newport', 'School Scores': ['17.6', '17.7', '18.0'], 'CAGR': 0.041151663495705204}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8b9'), 'Metro': 'Newport', 'Region': 'Cosby', 'School Scores': ['17.6', '17.7', '18.0'], 'CAGR': 0.018729585592748066}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ba'), 'Metro': 'Newport', 'Region': 'Parrottsville', 'School Scores': ['17.6', '17.7', '18.0'], 'CAGR': 0.03492116375938448}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8bb'), 'Metro': 'Newport', 'Region': 'Bybee', 'School Scores': ['17.6', '17.7', '18.0'], 'CAGR': 0.04816018015957613}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8bc'), 'Metro': 'Tullahoma', 'Region': 'Tullahoma', 'School Scores': ['18.6', '18.9', '19.2'], 'CAGR': 0.040042971658652116}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8bd'), 'Metro': 'Tullahoma', 'Region': 'Manchester', 'School Scores': ['18.6', '18.9', '19.2'], 'CAGR': 0.033338149506789705}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8be'), 'Metro': 'Tullahoma', 'Region': 'Normandy', 'School Scores': ['18.6', '18.9', '19.2'], 'CAGR': 0.04654722718131965}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8bf'), 'Metro': 'Tullahoma', 'Region': 'Hillsboro', 'School Scores': ['18.6', '18.9', '19.2'], 'CAGR': 0.039246516995844694}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c0'), 'Metro': 'Tullahoma', 'Region': 'Beechgrove', 'School Scores': ['18.6', '18.9', '19.2'], 'CAGR': 0.019301197698436523}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c1'), 'Metro': 'Crossville', 'Region': 'Crossville', 'School Scores': ['19.1', '19.1', '19.5'], 'CAGR': 0.04353482636514028}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c2'), 'Metro': 'Crossville', 'Region': 'Crab Orchard', 'School Scores': ['19.1', '19.1', '19.5'], 'CAGR': 0.048362774073928305}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c3'), 'Metro': nan, 'Region': 'Decaturville', 'School Scores': ['18.0', '18.5', '18.5'], 'CAGR': 0.027930137179335235}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c4'), 'Metro': nan, 'Region': 'Parsons', 'School Scores': ['18.0', '18.5', '18.5'], 'CAGR': 0.022912214091739935}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c5'), 'Metro': nan, 'Region': 'Bath Springs', 'School Scores': ['18.0', '18.5', '18.5'], 'CAGR': 0.011989726810221368}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c6'), 'Metro': nan, 'Region': 'Alexandria', 'School Scores': ['18.4', '18.7', '17.8'], 'CAGR': 0.058938643419665926}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c7'), 'Metro': 'Nashville', 'Region': 'Dickson', 'School Scores': ['19.3', '19.6', '19.2'], 'CAGR': 0.04749276603977526}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c8'), 'Metro': 'Nashville', 'Region': 'White Bluff', 'School Scores': ['19.3', '19.6', '19.2'], 'CAGR': 0.04181648699763385}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8c9'), 'Metro': 'Nashville', 'Region': 'Burns', 'School Scores': ['19.3', '19.6', '19.2'], 'CAGR': 0.05098067405289397}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ca'), 'Metro': 'Nashville', 'Region': 'Charlotte', 'School Scores': ['19.3', '19.6', '19.2'], 'CAGR': 0.02530876093405965}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8cb'), 'Metro': 'Nashville', 'Region': 'Vanleer', 'School Scores': ['19.3', '19.6', '19.2'], 'CAGR': 0.02892924516396267}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8cc'), 'Metro': 'Dyersburg', 'Region': 'Dyersburg', 'School Scores': ['19.2', '19.2', '19.9'], 'CAGR': 0.03647356994074413}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8cd'), 'Metro': 'Dyersburg', 'Region': 'Newbern', 'School Scores': ['19.2', '19.2', '19.9'], 'CAGR': 0.03521734529762832}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ce'), 'Metro': 'Dyersburg', 'Region': 'Finley', 'School Scores': ['19.2', '19.2', '19.9'], 'CAGR': 0.035183003715072436}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8cf'), 'Metro': 'Dyersburg', 'Region': 'Trimble', 'School Scores': ['19.2', '19.2', '19.9'], 'CAGR': 0.058372178232589}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d0'), 'Metro': 'Memphis', 'Region': 'Somerville', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.0007047223346843268}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d1'), 'Metro': 'Memphis', 'Region': 'Oakland', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.008906592508905797}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d2'), 'Metro': 'Memphis', 'Region': 'Hickory Withe', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.018280274158443577}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d3'), 'Metro': 'Memphis', 'Region': 'Moscow', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.003105649876241401}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d4'), 'Metro': 'Memphis', 'Region': 'Piperton', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.0276134806246755}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d5'), 'Metro': 'Memphis', 'Region': 'Williston', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.008958161243851404}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d6'), 'Metro': 'Memphis', 'Region': 'Rossville', 'School Scores': ['16.0', '16.2', '16.7'], 'CAGR': 0.046257984427653165}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d7'), 'Metro': nan, 'Region': 'Jamestown', 'School Scores': ['18.8', '18.8', '17.7'], 'CAGR': 0.0027742637286147787}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d8'), 'Metro': nan, 'Region': 'Clarkrange', 'School Scores': ['18.8', '18.8', '17.7'], 'CAGR': -0.0031418104121144763}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8d9'), 'Metro': nan, 'Region': 'Allardt', 'School Scores': ['18.8', '18.8', '17.7'], 'CAGR': 0.018973675413189284}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8da'), 'Metro': 'Tullahoma', 'Region': 'Winchester', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.03350654625217264}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8db'), 'Metro': 'Tullahoma', 'Region': 'Sewanee', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.01650545053141106}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8dc'), 'Metro': 'Tullahoma', 'Region': 'Decherd', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.04559413541903079}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8dd'), 'Metro': 'Tullahoma', 'Region': 'Huntland', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.028080976508138678}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8de'), 'Metro': 'Tullahoma', 'Region': 'Estill Springs', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.036519209464036084}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8df'), 'Metro': 'Tullahoma', 'Region': 'Belvidere', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.03650217723167426}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e0'), 'Metro': 'Tullahoma', 'Region': 'Cowan', 'School Scores': ['18.8', '18.8', '18.6'], 'CAGR': 0.04322916849742686}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e1'), 'Metro': nan, 'Region': 'Humboldt', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.012932739252421888}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e2'), 'Metro': nan, 'Region': 'Milan', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': -0.0011135885095092668}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e3'), 'Metro': nan, 'Region': 'Medina', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.01209077673627923}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e4'), 'Metro': nan, 'Region': 'Dyer', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.027713670256726886}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e5'), 'Metro': nan, 'Region': 'Trenton', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.036391414929932475}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e6'), 'Metro': nan, 'Region': 'Bradford', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.030521238754217084}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e7'), 'Metro': nan, 'Region': 'Kenton', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.030652421159365284}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e8'), 'Metro': nan, 'Region': 'Rutherford', 'School Scores': ['18.7', '18.8', '19.7'], 'CAGR': 0.030624138001266177}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8e9'), 'Metro': nan, 'Region': 'Pulaski', 'School Scores': ['18.0', '18.4', '18.0'], 'CAGR': 0.04501623696479751}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ea'), 'Metro': nan, 'Region': 'Lynnville', 'School Scores': ['18.0', '18.4', '18.0'], 'CAGR': 0.007625953229201343}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8eb'), 'Metro': nan, 'Region': 'Ardmore', 'School Scores': ['18.0', '18.4', '18.0'], 'CAGR': 0.04208085553999674}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ec'), 'Metro': nan, 'Region': 'Prospect', 'School Scores': ['18.0', '18.4', '18.0'], 'CAGR': 0.04062941312869128}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ed'), 'Metro': 'Knoxville', 'Region': 'Rutledge', 'School Scores': ['18.4', '18.7', '18.4'], 'CAGR': 0.040768348969842716}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ee'), 'Metro': 'Knoxville', 'Region': 'Bean Station', 'School Scores': ['18.4', '18.7', '18.4'], 'CAGR': 0.026292946198310352}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ef'), 'Metro': 'Greeneville', 'Region': 'Greeneville', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.023023396863666612}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f0'), 'Metro': 'Greeneville', 'Region': 'Chuckey', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.025011938465425487}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f1'), 'Metro': 'Greeneville', 'Region': 'Mosheim', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.03414337602940676}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f2'), 'Metro': 'Greeneville', 'Region': 'Tusculum', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.028283741531263562}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f3'), 'Metro': 'Greeneville', 'Region': 'Mohawk', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.03783677557113929}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f4'), 'Metro': 'Greeneville', 'Region': 'Midway', 'School Scores': ['18.9', '18.9', '19.4'], 'CAGR': 0.03909293608258202}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f5'), 'Metro': nan, 'Region': 'Gruetli Laager', 'School Scores': ['17.4', '17.5', '17.7'], 'CAGR': 0.07656303628261663}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f6'), 'Metro': 'Morristown', 'Region': 'Morristown', 'School Scores': ['20.0', '20.1', '19.2'], 'CAGR': 0.01970544824592535}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f7'), 'Metro': 'Morristown', 'Region': 'Talbott', 'School Scores': ['20.0', '20.1', '19.2'], 'CAGR': 0.022412705578087166}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f8'), 'Metro': 'Morristown', 'Region': 'Russellville', 'School Scores': ['20.0', '20.1', '19.2'], 'CAGR': 0.025092500124230366}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8f9'), 'Metro': 'Morristown', 'Region': 'Whitesburg', 'School Scores': ['20.0', '20.1', '19.2'], 'CAGR': 0.02659477761368123}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8fa'), 'Metro': 'Chattanooga', 'Region': 'Chattanooga', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.02663207030572079}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8fb'), 'Metro': 'Chattanooga', 'Region': 'East Ridge', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.019391330247987337}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8fc'), 'Metro': 'Chattanooga', 'Region': 'Ooltewah', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.02774482551380575}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8fd'), 'Metro': 'Chattanooga', 'Region': 'East Brainerd', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.020241640745055633}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8fe'), 'Metro': 'Chattanooga', 'Region': 'Middle Valley', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.02693231968612997}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c8ff'), 'Metro': 'Chattanooga', 'Region': 'Harrison', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.020771408223331678}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c900'), 'Metro': 'Chattanooga', 'Region': 'Red Bank', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.023150767297561492}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c901'), 'Metro': 'Chattanooga', 'Region': 'Soddy-Daisy', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.023951332113893775}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c902'), 'Metro': 'Chattanooga', 'Region': 'Signal Mountain', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.029868916766364162}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c903'), 'Metro': 'Chattanooga', 'Region': 'Collegedale', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.016696884078246432}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c904'), 'Metro': 'Chattanooga', 'Region': 'Lakesite', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.018066425813406672}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c905'), 'Metro': 'Chattanooga', 'Region': 'Walden', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.019724097821332}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c906'), 'Metro': 'Chattanooga', 'Region': 'Fairmount', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.02317867357657266}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c907'), 'Metro': 'Chattanooga', 'Region': 'Sale Creek', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.024741825906461123}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c908'), 'Metro': 'Chattanooga', 'Region': 'Lookout Mountain', 'School Scores': ['18.7', '18.9', '19.0'], 'CAGR': 0.0333953582417279}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c909'), 'Metro': nan, 'Region': 'Bolivar', 'School Scores': ['16.9', '17.3', '17.1'], 'CAGR': nan}
{'_id': ObjectId('5f4eeeebdb91df5fb0c3c90a'), 'Metro': nan, 'Region': 'Savannah', 'School Scores': ['18.5', '19.1', '18.9'], 'CAGR': 0.023558642631228643}

In [ ]:
dict2 = clean_df.to_dict()
dict2